#${artifactId.toLowerCase().replace("-", "")}:
#  image: suzel/${artifactId.toLowerCase().replace("-", "")}
#  ports:
#    - "8080:8080"
#  links:
#    - mysql:mysql
#    - postgres:postgres
#    - mongodb:mongodb
#    - redis:redis
#    - elasticsearch:elasticsearch
#  volumes:
#    - www:/var/www

#mysql:
#  image: mysql
#  ports:
#    - "3306:3306"
#  environment:
#    MYSQL_DATABASE: ${artifactId.toLowerCase()}_db
#    MYSQL_USER: ${artifactId.toLowerCase()}_user
#    MYSQL_PASSWORD: password
#    MYSQL_ROOT_PASSWORD: password

#postgres:
#  image: postgres
#  ports:
#    - "5432:5432"
#  environment:
#    POSTGRES_DB: ${artifactId.toLowerCase()}_db
#    POSTGRES_USER: ${artifactId.toLowerCase()}_user
#    POSTGRES_PASSWORD: password

#mongodb:
#  image: mongo
#  ports:
#    - "27017:27017"

#redis:
#  image: tutum/redis
#  ports:
#    - "6379:6379"
#  environment:
#    REDIS_PASS: password

#elasticsearch:
#  image: elasticsearch
#  ports:
#    - "9200:9200"
#    - "9300:9300"

#kafka:
#  image: wurstmeister/kafka
#  ports:
#    - "9092:9092"
